init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
#test: off
version: 0.2.0.{build}
artifacts:
  - path: bin
    name: bin
  - path: bin\*.nupkg
    name: appveyor-nuget
    