matrix:
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release


init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd

version: 0.2.0.{build}

# scripts to run before build
before_build:
  - .paket/paket restore
