os: Windows Server 2012 R2

shallow_clone: true

version: 0.2.0.{build}

matrix:
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release

clone_folder: c:\projects\libwebp-net


# scripts that run after cloning repository
install:
  - del C:\projects\libwebp-net\x86\libwebp.dll
  - del C:\projects\libwebp-net\x64\libwebp.dll
  - cd C:\projects
  - git clone https://chromium.googlesource.com/webm/libwebp --branch 0.4.1 --depth 1
  - cd C:\projects\libwebp
  - "\"C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Bin\\SetEnv.cmd\" /x64"
  - "nmake /f Makefile.vc CFG=release-dynamic RTLIBCFG=dynamic OBJDIR=output"
  - copy /Y C:\projects\libwebp\output\release-dynamic\x64\bin\libwebp.dll C:\projects\libwebp-net\x64\
  - appveyor PushArtifact C:\projects\libwebp\output\release-dynamic\x64\bin\libwebp.dll -FileName libwebp(x64).dll
  - "\"C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Bin\\SetEnv.cmd\" /x86"
  - "nmake /f Makefile.vc CFG=release-dynamic RTLIBCFG=dynamic OBJDIR=output"
  - copy /Y C:\projects\libwebp\output\release-dynamic\x86\bin\libwebp.dll C:\projects\libwebp-net\x86\
  - appveyor PushArtifact C:\projects\libwebp\output\release-dynamic\x86\bin\libwebp.dll -FileName libwebp(x86).dll
#---------------------------------#
#       build configuration       #
#---------------------------------#

test_script:
  - xunit.console.clr4.exe Imazen.Test.WebP\bin\Release\Imazen.Test.Webp.dll /appveyor
  - xunit.console.clr4.x86.exe Imazen.Test.WebP\bin\Release\Imazen.Test.Webp.dll /appveyor

init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off
version: 0.2.0.{build}
  

artifacts:
  - path: output\release-dynamic\x64\bin\libwebp.dll
    name: libwebbp-x64.dll
  - path: output\release-dynamic\x86\bin\libwebp.dll
    name: libwebbp-x86.dll
